<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-IASR4KE" failures="2" tests="5" name="Test1" time="1247.807" errors="0" timestamp="2022-02-10T15:43:27 ICT">
  <testcase classname="tests.LoginTest" name="loginWithBlankField" time="1.171"/>
  <testcase classname="tests.LoginTest" name="loginByAdmin" time="10.845">
    <failure type="org.awaitility.core.ConditionTimeoutException" message="Condition with tests.LoginTest was not fulfilled within 10 seconds.">
      <![CDATA[org.awaitility.core.ConditionTimeoutException: Condition with tests.LoginTest was not fulfilled within 10 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:864)
at tests.LoginTest.loginByAdmin(LoginTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.getCurrentUrl()" because the return value of "tests.LoginTest.getDriver()" is null
at tests.LoginTest.lambda$0(LoginTest.java:39)
at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
... 4 more
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- loginByAdmin -->
  <testcase classname="tests.InvM_InvoiceListTest" name="clickInvoiceManagement" time="0.098"/>
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadon1dongSuccess" time="39.924"/>
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadonnhieudongSuccess" time="1191.421">
    <failure type="java.lang.Exception" message="SAI O HANG HOA Điện thoại sam sung galaxy a10O HOA DON0">
      <![CDATA[java.lang.Exception: SAI O HANG HOA Điện thoại sam sung galaxy a10O HOA DON0
at pages.InvM_InvoiceListPage.lapHoaDon(InvM_InvoiceListPage.java:203)
at tests.InvM_InvoiceListTest.laphoadonnhieudongSuccess(InvM_InvoiceListTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- laphoadonnhieudongSuccess -->
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadonFail1" time="0.0">
    <ignored/>
  </testcase> <!-- laphoadonFail1 -->
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadonFail2" time="0.0">
    <ignored/>
  </testcase> <!-- laphoadonFail2 -->
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadonFail3" time="0.0">
    <ignored/>
  </testcase> <!-- laphoadonFail3 -->
  <testcase classname="tests.BaseTest" name="@AfterTest tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="tests.BaseTest" name="@BeforeTest setUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest setUp -->
</testsuite> <!-- Test1 -->
