<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IASR4KE" failures="0" tests="3" name="tests.InvM_InvoiceListTest" time="1231.443" errors="1" timestamp="2022-02-10T15:43:27 ICT" skipped="0">
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadonnhieudongSuccess" time="1191.421">
    <error message="SAI O HANG HOA Điện thoại sam sung galaxy a10O HOA DON0" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: SAI O HANG HOA Điện thoại sam sung galaxy a10O HOA DON0
at pages.InvM_InvoiceListPage.lapHoaDon(InvM_InvoiceListPage.java:203)
at tests.InvM_InvoiceListTest.laphoadonnhieudongSuccess(InvM_InvoiceListTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- laphoadonnhieudongSuccess -->
  <system-out/>
  <testcase classname="tests.InvM_InvoiceListTest" name="clickInvoiceManagement" time="0.098"/>
  <system-out/>
  <testcase classname="tests.InvM_InvoiceListTest" name="laphoadon1dongSuccess" time="39.924"/>
  <system-out/>
</testsuite> <!-- tests.InvM_InvoiceListTest -->
